title: TechSimplified
description: "Making technology simple. Guides, tips, and how-tos for everyday tech."
url: "https://kkumakkuma.github.io"
baseurl: "/TechSimplified"
permalink: /:year/:month/:day/:title/
future: true

theme: minima

author:
  name: TechSimplified
  email: ""

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true

google_analytics: "G-5L40K3SBQT"

exclude:
  - scripts/
  - .github/
  - README.md
  - Gemfile
  - Gemfile.lock
